/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.Administrador;

import DTO.Comuna;
import DTO.Recinto;
import DTO.Ubicacion;
import java.util.ArrayList;
import javax.swing.JOptionPane;



/**
 *
 * @author emmanuel.padilla
 */
public class AdministradorDeRecintos extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private DTO.Usuario usuario;
    private ArrayList<Recinto> recintos;
    private ArrayList<Ubicacion> ubicaciones;

    
    public AdministradorDeRecintos() {
        
        initComponents();
        this.setLocationRelativeTo(null);
        pnlRecinto.setVisible(false);
        pnlUbicacion.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCabezera = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlRecinto = new javax.swing.JPanel();
        jLabelNombre = new javax.swing.JLabel();
        txtNombreRecinto = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabelCapacidadMaxima = new javax.swing.JLabel();
        txtCapacidadMaxima = new javax.swing.JTextField();
        cmbComuna = new javax.swing.JComboBox<>();
        jLabelComuna = new javax.swing.JLabel();
        jLabelFono = new javax.swing.JLabel();
        txtFono = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabelCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableRecintosListar = new javax.swing.JTable();
        btnListarRecintos = new javax.swing.JButton();
        pnlUbicacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtcodigoUbicacion = new javax.swing.JTextField();
        cmbFila = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cmbRecinto = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnCrearUbicacion = new javax.swing.JButton();
        btnModificarUbicacion = new javax.swing.JButton();
        btnEliminarUbicacion = new javax.swing.JButton();
        btnBuscarUbicacion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableUbicacionesListar = new javax.swing.JTable();
        btnListarUbicaciones = new javax.swing.JButton();
        btnUbicacion = new javax.swing.JButton();
        btnRecinto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Creación de usuarios");
        setMaximumSize(new java.awt.Dimension(800, 700));
        setPreferredSize(new java.awt.Dimension(800, 700));

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabelTitulo.setText("Administrador de Recintos");

        javax.swing.GroupLayout jPanelCabezeraLayout = new javax.swing.GroupLayout(jPanelCabezera);
        jPanelCabezera.setLayout(jPanelCabezeraLayout);
        jPanelCabezeraLayout.setHorizontalGroup(
            jPanelCabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabezeraLayout.createSequentialGroup()
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelCabezeraLayout.setVerticalGroup(
            jPanelCabezeraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCabezeraLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(620, 400));

        jLabelNombre.setText("Nombre Recinto");

        lblDireccion.setText("Dirección");

        jLabelCapacidadMaxima.setText("Capacidad Maxima");

        cmbComuna.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cerrillos", "Cerro Navia", "Conchalí", "El bosque", "Estación Central", "Huechuraba", "Independencia", "La Cisterna", "La Florida", "La Pintana", "La Granja", "La Reina", "Las Condes", "Lo Barnechea", "Lo Espejo", "Lo Prado", "Macul", "Maipú", "Ñuñoa", "Pedro Aguirre Cerda", "Peñalolén", "Providencia", "Pudahuel", "Quilicura", "Quinta Normal", "Recoleta", "Renca", "San Miguel", "San Joaquín", "San Ramón", "Santiago", "Vitacura", "Padre Hurtado", "Pirque", "San Bernardo", "San José de Maipo", "Puente Alto" }));

        jLabelComuna.setText("Comuna");

        jLabelFono.setText("Fono");

        btnCrear.setText("Crear ");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar ");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabelCodigo.setText("Codigo");

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(null);

        jTableRecintosListar.setModel(new Util.jTableCustom.Models.jTableModelRecinto());
        jScrollPane1.setViewportView(jTableRecintosListar);

        btnListarRecintos.setText("Listar Recintos");
        btnListarRecintos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarRecintosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRecintoLayout = new javax.swing.GroupLayout(pnlRecinto);
        pnlRecinto.setLayout(pnlRecintoLayout);
        pnlRecintoLayout.setHorizontalGroup(
            pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecintoLayout.createSequentialGroup()
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecintoLayout.createSequentialGroup()
                        .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlRecintoLayout.createSequentialGroup()
                                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelCodigo)
                                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelComuna)
                                    .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(pnlRecintoLayout.createSequentialGroup()
                                            .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtCapacidadMaxima))
                                        .addGroup(pnlRecintoLayout.createSequentialGroup()
                                            .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(txtNombreRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabelNombre))
                                            .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnlRecintoLayout.createSequentialGroup()
                                                    .addGap(11, 11, 11)
                                                    .addComponent(jLabelFono))
                                                .addGroup(pnlRecintoLayout.createSequentialGroup()
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                    .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelCapacidadMaxima)
                                                        .addComponent(txtFono, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                            .addGroup(pnlRecintoLayout.createSequentialGroup()
                                .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar))
                    .addComponent(btnListarRecintos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pnlRecintoLayout.setVerticalGroup(
            pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecintoLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(jLabelCodigo)
                    .addComponent(jLabelFono))
                .addGap(7, 7, 7)
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(jLabelComuna)
                    .addComponent(jLabelCapacidadMaxima))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCapacidadMaxima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlRecintoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnBuscar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(btnListarRecintos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlUbicacion.setPreferredSize(new java.awt.Dimension(600, 360));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Registro de Ubicaciones");

        jLabel2.setText("Código");

        cmbFila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z" }));

        jLabel3.setText("Fila");

        cmbRecinto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Recinto");

        btnCrearUbicacion.setText("Crear");
        btnCrearUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearUbicacionActionPerformed(evt);
            }
        });

        btnModificarUbicacion.setText("Modificar");
        btnModificarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUbicacionActionPerformed(evt);
            }
        });

        btnEliminarUbicacion.setText("eliminar");

        btnBuscarUbicacion.setText("Buscar");
        btnBuscarUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarUbicacionActionPerformed(evt);
            }
        });

        jTableUbicacionesListar.setModel(new Util.jTableCustom.Models.jTableModelUbicaciones());
        jScrollPane2.setViewportView(jTableUbicacionesListar);

        btnListarUbicaciones.setText("Listar");
        btnListarUbicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarUbicacionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUbicacionLayout = new javax.swing.GroupLayout(pnlUbicacion);
        pnlUbicacion.setLayout(pnlUbicacionLayout);
        pnlUbicacionLayout.setHorizontalGroup(
            pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUbicacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(pnlUbicacionLayout.createSequentialGroup()
                            .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtcodigoUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(28, 28, 28)
                            .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbFila, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(cmbRecinto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(pnlUbicacionLayout.createSequentialGroup()
                            .addComponent(btnCrearUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnBuscarUbicacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnModificarUbicacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnEliminarUbicacion)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarUbicaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        pnlUbicacionLayout.setVerticalGroup(
            pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUbicacionLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigoUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbFila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUbicacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearUbicacion)
                    .addComponent(btnModificarUbicacion)
                    .addComponent(btnEliminarUbicacion)
                    .addComponent(btnBuscarUbicacion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(btnListarUbicaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        btnUbicacion.setText("Administrar Ubicación");
        btnUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbicacionActionPerformed(evt);
            }
        });

        btnRecinto.setText("Administrar Recinto");
        btnRecinto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecintoActionPerformed(evt);
            }
        });

        jLayeredPane1.setLayer(pnlRecinto, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(pnlUbicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnUbicacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(btnRecinto, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(btnRecinto)
                        .addGap(30, 30, 30)
                        .addComponent(btnUbicacion))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(pnlRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap(34, Short.MAX_VALUE)
                        .addComponent(pnlRecinto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRecinto)
                    .addComponent(btnUbicacion))
                .addGap(24, 24, 24))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelCabezera, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(377, 377, 377))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCabezera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        DTO.Recinto recinto = new DTO.Recinto();
        DTO.Comuna comuna = new DTO.Comuna();
        try {
            recinto.setCodigo(Integer.parseInt(txtCodigo.getText()));
            recinto.setNombre(txtNombreRecinto.getText());
            recinto.setFono(Integer.parseInt(txtFono.getText()));
            recinto.setDireccion(txtDireccion.getText());
            comuna.setCodigo(cmbComuna.getSelectedIndex()+1);
            comuna.setNombre(cmbComuna.getSelectedItem().toString());            
            recinto.setComuna(comuna);
            recinto.setCapacidadMaxima(Integer.parseInt(txtCapacidadMaxima.getText()));
                   
            new DAO.ImplRecintoDAO().ModificarRecinto(recinto);
            
            JOptionPane.showMessageDialog(this,
                "Recinto modificado con exito",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se puedo modificar el recinto" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        DTO.Recinto recinto = new DTO.Recinto();
        DTO.Comuna comuna = new DTO.Comuna();
        try {
            recinto = new DAO.ImplRecintoDAO().ObtenerRecinto(Integer.parseInt(txtCodigo.getText()));
            
            Integer codigo = recinto.getCodigo();
            txtCodigo.setText(codigo.toString());
            txtNombreRecinto.setText(recinto.getNombre());
            txtDireccion.setText(recinto.getDireccion());            
            cmbComuna.setSelectedItem(comuna.getNombre());
            Integer fono = recinto.getFono();
            txtFono.setText(fono.toString());
            Integer capacidadMaxima = recinto.getCapacidadMaxima();
            txtCapacidadMaxima.setText(capacidadMaxima.toString());
                               
            
            
            JOptionPane.showMessageDialog(this,
                "Datos de recinto cargados con exito",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se pudieron cargar los datos del recinto" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        DTO.Recinto recinto = new DTO.Recinto();
        DTO.Comuna comuna = new DTO.Comuna();
        try {
            recinto.setNombre(txtNombreRecinto.getText());          
            recinto.setDireccion(txtDireccion.getText());
            comuna.setCodigo(cmbComuna.getSelectedIndex()+1);
            comuna.setNombre(cmbComuna.getSelectedItem().toString());
            recinto.setComuna(comuna);
            recinto.setFono(Integer.parseInt(txtFono.getText()));
            recinto.setCapacidadMaxima(Integer.parseInt(txtCapacidadMaxima.getText()));
                   
            new DAO.ImplRecintoDAO().CrearRecinto(recinto);
            
            JOptionPane.showMessageDialog(this,
                "Recinto agregado exitosamente",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se pudo registrar el recinto" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
       DTO.Recinto recinto = new DTO.Recinto();
        recinto.setCodigo(Integer.parseInt(txtCodigo.getText()));
 
        try {
            new DAO.ImplRecintoDAO().EliminarRecinto(recinto);
            JOptionPane.showMessageDialog(this,
                "Recinto eliminado exitosamente",
                "Eliminado",
                JOptionPane.PLAIN_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se pudo eliminar el recinto" +e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void btnRecintoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecintoActionPerformed
        pnlRecinto.setVisible(true);
        pnlUbicacion.setVisible(false);
    }//GEN-LAST:event_btnRecintoActionPerformed

    private void btnUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbicacionActionPerformed
        pnlUbicacion.setVisible(true);
        pnlRecinto.setVisible(false);
    }//GEN-LAST:event_btnUbicacionActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCodigo.setText("");
        txtNombreRecinto.setText("");
        txtDireccion.setText("");
        txtFono.setText("");
        txtCapacidadMaxima.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnListarRecintosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarRecintosActionPerformed
        
        this.refrescarListaRecintos();
    }//GEN-LAST:event_btnListarRecintosActionPerformed

    private void btnCrearUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearUbicacionActionPerformed
      DTO.Ubicacion ubicacion = new Ubicacion();
        
        try {
            ubicacion.setFila(cmbFila.getName().charAt(0));
            ubicacion.setRecinto(cmbRecinto.getSelectedIndex());
                   
            new DAO.ImplRecintoDAO().CrearUbicacion(ubicacion);
            
            JOptionPane.showMessageDialog(this,
                "Ubicacion agregada exitosamente",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se registrar la ubicación" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearUbicacionActionPerformed

    private void btnBuscarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarUbicacionActionPerformed
        
        DTO.Ubicacion ubicacion = new DTO.Ubicacion();
        try {
            
            Integer codigo = ubicacion.getCodigo();
            txtCodigo.setText(codigo.toString());  
            Character fila = ubicacion.getFila();
            cmbComuna.setName(fila.toString()); //PENDIENTE
            cmbRecinto.setSelectedIndex(ubicacion.getRecinto());
            
            new DAO.ImplRecintoDAO().ModificarUbicacion(ubicacion);
            
            JOptionPane.showMessageDialog(this,
                "Datos de ubicacion cargados con exito",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se puedieron cargar los datos de la ubicación" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarUbicacionActionPerformed

    private void btnModificarUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUbicacionActionPerformed
        DTO.Ubicacion ubicacion = new DTO.Ubicacion();
        try {
            ubicacion.setCodigo(Integer.parseInt(txtcodigoUbicacion.getText()));
            ubicacion.setFila(cmbFila.getName().charAt(0));
            ubicacion.setRecinto(cmbRecinto.getSelectedIndex()+1);           
                   
            new DAO.ImplRecintoDAO().ModificarUbicacion(ubicacion);
            
            JOptionPane.showMessageDialog(this,
                "Ubicacion modificada con exito",
                "Éxito",
                JOptionPane.PLAIN_MESSAGE);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "No se pudo modificar la ubicación" + e.getMessage(),
                "Error",
                JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnModificarUbicacionActionPerformed

    private void btnListarUbicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarUbicacionesActionPerformed
        this.refrescarListaUbicaciones();
    }//GEN-LAST:event_btnListarUbicacionesActionPerformed
    
    
    private void refrescarListaRecintos() {
       ((Util.jTableCustom.Models.jTableModelRecinto)jTableRecintosListar.getModel()).removerDatos();
       
       this.recintos = new DAO.ImplRecintoDAO().RecuperarRecinto_Todos();
       recintos.forEach((recintos) -> {
           ((Util.jTableCustom.Models.jTableModelRecinto)jTableRecintosListar.getModel()).cargarDatos(recintos);
       } );
       ((Util.jTableCustom.Models.jTableModelRecinto)this.jTableRecintosListar.getModel()).isCellEditable(0, 0);
    }
    
    private void refrescarListaUbicaciones() {
       ((Util.jTableCustom.Models.jTableModelUbicaciones)jTableUbicacionesListar.getModel()).removerDatos();
       
       this.ubicaciones = new DAO.ImplRecintoDAO().RecuperarUbicacionesPorRecinto(cmbRecinto.getSelectedIndex()+1);
       ubicaciones.forEach((ubicaciones) -> {
           ((Util.jTableCustom.Models.jTableModelUbicaciones)jTableUbicacionesListar.getModel()).cargarDatos(ubicaciones);
       } );
       ((Util.jTableCustom.Models.jTableModelUbicaciones)this.jTableUbicacionesListar.getModel()).isCellEditable(0, 0);
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeRecintos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeRecintos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeRecintos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministradorDeRecintos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministradorDeRecintos().setVisible(true);
            }
        });
    }
    
    
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarUbicacion;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton btnCrearUbicacion;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarUbicacion;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnListarRecintos;
    private javax.swing.JButton btnListarUbicaciones;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnModificarUbicacion;
    private javax.swing.JButton btnRecinto;
    private javax.swing.JButton btnUbicacion;
    private javax.swing.JComboBox<String> cmbComuna;
    private javax.swing.JComboBox<String> cmbFila;
    private javax.swing.JComboBox<String> cmbRecinto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCapacidadMaxima;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelComuna;
    private javax.swing.JLabel jLabelFono;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelCabezera;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableRecintosListar;
    private javax.swing.JTable jTableUbicacionesListar;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JPanel pnlRecinto;
    private javax.swing.JPanel pnlUbicacion;
    private javax.swing.JTextField txtCapacidadMaxima;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFono;
    private javax.swing.JTextField txtNombreRecinto;
    private javax.swing.JTextField txtcodigoUbicacion;
    // End of variables declaration//GEN-END:variables
}
